### ISSUE TITLE
u.save() error on register new user

### ISSUE THREAD

**Issue by Purzelkater** [Kruptein/PlanarAlly#101]
I'm so sorry, but after installing 0.11.1 I have the next problem now. Well the server is running as expected. But if I try to register a new user, it fails with
```
500 Internal Server Error
Server got itself in trouble
```
on the browser. The console log shows me
```
Error handling request
Traceback (most recent call last):
  File "D:\Python\Python37\lib\site-packages\peewee.py", line 2683, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.IntegrityError: NOT NULL constraint failed: user.name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python\Python37\lib\site-packages\aiohttp\web_protocol.py", line 390, in start
    resp = await self._request_handler(request)
  File "D:\Python\Python37\lib\site-packages\aiohttp\web_app.py", line 366, in _handle
    resp = await handler(request)
  File "D:\Python\Python37\lib\site-packages\aiohttp\web_middlewares.py", line 106, in impl
    return await handler(request)
  File "D:\Python\Python37\lib\site-packages\aiohttp_session\__init__.py", line 152, in factory
    response = await handler(request)
  File "D:\Python\Python37\lib\site-packages\aiohttp_jinja2\__init__.py", line 91, in wrapped
    context = await coro(*args)
  File "D:\Python\PlanarAlly\PlanarAlly\routes.py", line 33, in login
    u.save()
  File "D:\Python\Python37\lib\site-packages\playhouse\signals.py", line 71, in save
    ret = super(Model, self).save(*args, **kwargs)
  File "D:\Python\Python37\lib\site-packages\peewee.py", line 5678, in save
    pk_from_cursor = self.insert(**field_dict).execute()
  File "D:\Python\Python37\lib\site-packages\peewee.py", line 1604, in inner
    return method(self, database, *args, **kwargs)
  File "D:\Python\Python37\lib\site-packages\peewee.py", line 1675, in execute
    return self._execute(database)
  File "D:\Python\Python37\lib\site-packages\peewee.py", line 2331, in _execute
    return super(Insert, self)._execute(database)
  File "D:\Python\Python37\lib\site-packages\peewee.py", line 2097, in _execute
    cursor = database.execute(self)
  File "D:\Python\Python37\lib\site-packages\peewee.py", line 2696, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "D:\Python\Python37\lib\site-packages\peewee.py", line 2690, in execute_sql
    self.commit()
  File "D:\Python\Python37\lib\site-packages\peewee.py", line 2481, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "D:\Python\Python37\lib\site-packages\peewee.py", line 178, in reraise
    raise value.with_traceback(tb)
  File "D:\Python\Python37\lib\site-packages\peewee.py", line 2683, in execute_sql
    cursor.execute(sql, params or ())
peewee.IntegrityError: NOT NULL constraint failed: user.name
```
I would say, the problem is on the user save function, called as u.save() on line 33 on routes.py. Sadly I'm not familiar with Python, but could it be the problem depends on line 31 "u = User(username)"? This should create a new user object with the username but I'm not sure, because I haven't seen a set_user or something like a new(user) function on user.py.

**Comment by Kruptein** [comment]
Hey no problem, this is a very big change so any bug you find is nice.

That said, I noticed this bug myself and apparently failed to correctly push it to the server,
it should take me ~5 minutes to fix.

The line should read `u = User(name=username)` btw ;), the issue has to do mostly with the database orm.

**Comment by Purzelkater** [comment]
> The line should read `u = User(name=username)` btw ;)

Ah, okay, now this makes sense :)

**Comment by Purzelkater** [comment]
Had the same error with 0.11.2, but was easy fixable now with
`u = User(name=username)`
because on user.py the username is declared as "name", not "user" :)
You had `u = User(user=username)` on routes.py.

**Comment by Kruptein** [comment]
haha wow that happens when you try to be quick I guess, well 0.11.3 here we come
