### ISSUE TITLE
Unable to add new location on 0.11.4

### ISSUE THREAD

**Issue by Purzelkater** [Kruptein/PlanarAlly#104]
If I try to add a new location I get an error after entering the location name:

```
message async handler error
Traceback (most recent call last):
  File "D:\Python\Python37\lib\site-packages\engineio\asyncio_server.py", line 278, in _trigger_event
    ret = await self.handlers[event](*args)
  File "D:\Python\Python37\lib\site-packages\socketio\asyncio_server.py", line 364, in _handle_eio_message
    await self._handle_event(sid, pkt.namespace, pkt.id, pkt.data)
  File "D:\Python\Python37\lib\site-packages\socketio\asyncio_server.py", line 294, in _handle_event
    await self._handle_event_internal(self, sid, data, namespace, id)
  File "D:\Python\Python37\lib\site-packages\socketio\asyncio_server.py", line 297, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "D:\Python\Python37\lib\site-packages\socketio\asyncio_server.py", line 325, in _trigger_event
    ret = await self.handlers[namespace][event](*args)
  File "D:\Python\PlanarAlly-0.11.4\PlanarAlly\auth.py", line 43, in wrapped
    return await fn(*args, **kwargs)
  File "D:\Python\PlanarAlly-0.11.4\PlanarAlly\api\location.py", line 129, in add_new_location
    new_location = Location.create(room=room, name=location.name)
AttributeError: 'str' object has no attribute 'name'
```

**Comment by Kruptein** [comment]
Fixed in 0.11.5
