### ISSUE TITLE
Drawing on FOW layer with brush leads to NOT NULL error

### ISSUE THREAD

**Issue by schemen** [Kruptein/PlanarAlly#114]
There seems to be a problem with the DB and peewee where a paced constraint doesn't work.
When trying to draw on the FOW layer with the bursh tool I get the following error:

```
message async handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2683, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.IntegrityError: NOT NULL constraint failed: multi_line.line_width

During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/engineio/asyncio_server.py", line 278, in _trigger_event
    ret = await self.handlers[event](*args)
  File "/usr/local/lib/python3.6/site-packages/socketio/asyncio_server.py", line 364, in _handle_eio_message
    await self._handle_event(sid, pkt.namespace, pkt.id, pkt.data)
  File "/usr/local/lib/python3.6/site-packages/socketio/asyncio_server.py", line 294, in _handle_event
    await self._handle_event_internal(self, sid, data, namespace, id)
  File "/usr/local/lib/python3.6/site-packages/socketio/asyncio_server.py", line 297, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/usr/local/lib/python3.6/site-packages/socketio/asyncio_server.py", line 325, in _trigger_event
    ret = await self.handlers[namespace][event](*args)
  File "/usr/src/app/auth.py", line 43, in wrapped
    return await fn(*args, **kwargs)
  File "/usr/src/app/api/shape.py", line 40, in add_shape
    **reduce_data_to_model(type_table, data["shape"]))
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 5531, in create
    inst.save(force_insert=True)
  File "/usr/local/lib/python3.6/site-packages/playhouse/signals.py", line 71, in save
    ret = super(Model, self).save(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 5675, in save
    self.insert(**field_dict).execute()
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 1604, in inner
    return method(self, database, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 1675, in execute
    return self._execute(database)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2331, in _execute
    return super(Insert, self)._execute(database)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2097, in _execute
    cursor = database.execute(self)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2696, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2690, in execute_sql
    self.commit()
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2481, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 178, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2683, in execute_sql
    cursor.execute(sql, params or ())
peewee.IntegrityError: NOT NULL constraint failed: multi_line.line_width
```

With a lot of messages from ` 2018-11-20 18:01:37,451 - WARNING - Attempt to update unknown shape by schemen (shape.py:88)`

This is with the running version on dndbox, 0.11.6. This also means that the drawn shape is not saved, thus not synced to the player view.

**Comment by Kruptein** [comment]
It should be fixed on `dev` now.

Do note that the brush is not supported on the fow layer in normal draw mode currently. I've fixed another issue in which the brush would completely block the entire render loop due to being added on the fow layer manually.

If you want to use the brush for vision, use it in the reveal/hide mode.
