### ISSUE TITLE
Upgrade 0.14.2 -> 0.15.0  seems to fail due to DB issue

### ISSUE THREAD

**Issue by schemen** [Kruptein/PlanarAlly#143]
Hi!

Trying to upgrade I get the following error for a duplicated entry: 

`Save format 12 does not match the required version 13!,
Attempting upgrade,
Backing up old save as /usr/src/app/data/planar.save.12,
Starting upgrade to 13,
duplicate column name: category,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2940, in execute_sql,
    cursor.execute(sql, params or ()),
sqlite3.OperationalError: duplicate column name: category,
,
During handling of the above exception, another exception occurred:,
,
Traceback (most recent call last):,
  File "/usr/src/app/save.py", line 173, in check_save,
    upgrade(constants.save_version),
  File "/usr/src/app/save.py", line 129, in upgrade,
    migrate(migrator.add_column("label", "category", Label.category)),
  File "/usr/local/lib/python3.6/site-packages/playhouse/migrate.py", line 823, in migrate,
    operation.run(),
  File "/usr/local/lib/python3.6/site-packages/playhouse/migrate.py", line 160, in run,
    self._handle_result(method(*self.args, **kwargs)),
  File "/usr/local/lib/python3.6/site-packages/playhouse/migrate.py", line 154, in _handle_result,
    self._handle_result(item),
  File "/usr/local/lib/python3.6/site-packages/playhouse/migrate.py", line 151, in _handle_result,
    result.run(),
  File "/usr/local/lib/python3.6/site-packages/playhouse/migrate.py", line 160, in run,
    self._handle_result(method(*self.args, **kwargs)),
  File "/usr/local/lib/python3.6/site-packages/playhouse/migrate.py", line 149, in _handle_result,
    self.execute(result),
  File "/usr/local/lib/python3.6/site-packages/playhouse/migrate.py", line 145, in execute,
    self.migrator.database.execute(node),
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2953, in execute,
    return self.execute_sql(sql, params, commit=commit),
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2947, in execute_sql,
    self.commit(),
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2729, in __exit__,
    reraise(new_type, new_type(*exc_args), traceback),
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 183, in reraise,
    raise value.with_traceback(tb),
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2940, in execute_sql,
    cursor.execute(sql, params or ()),
peewee.OperationalError: duplicate column name: category,
ERROR: Could not start server,`

Any idea? I have reverted to v0.14.2 for now

**Comment by Kruptein** [comment]
That ain't good I'll try to take a look later!

p.s. development has been slacking a bit due to a personal campaign taking quite some work, I'll try to get back into flow soon

**Comment by schemen** [comment]
Hey no worries haha! I was also away for quite a while now :)

**Comment by Kruptein** [comment]
This should be fixed in release 15.1, thanks for the report :)

**Comment by schemen** [comment]
Confirmed, it's working :)
