### ISSUE TITLE
Sessions with a space in their name do not work correctly

### ISSUE THREAD

**Issue by AntiSC2** [Kruptein/PlanarAlly#20]
When creating a session with a space in its name the board is completely white and most functions don't work. The output when creating or joining a session with a space:
```
message async handler error
Traceback (most recent call last):
  File "/home/jakob/.pyenv/versions/3.6.5/lib/python3.6/site-packages/engineio/asyncio_server.py", line 269, in _trigger_event
    ret = await self.handlers[event](*args)
  File "/home/jakob/.pyenv/versions/3.6.5/lib/python3.6/site-packages/socketio/asyncio_server.py", line 360, in _handle_eio_message
    await self._handle_connect(sid, pkt.namespace)
  File "/home/jakob/.pyenv/versions/3.6.5/lib/python3.6/site-packages/socketio/asyncio_server.py", line 257, in _handle_connect
    self.environ[sid]) is False:
  File "/home/jakob/.pyenv/versions/3.6.5/lib/python3.6/site-packages/socketio/asyncio_server.py", line 325, in _trigger_event
    ret = await self.handlers[namespace][event](*args)
  File "PlanarAlly/planarserver.py", line 494, in test_connect
KeyError: ('The%20Dead%20Exiles', 'Anti')
```
Username: Anti
Session name: The Dead Exiles
Python Version: 3.6.5
OS: Linux x64

**Comment by Kruptein** [comment]
Thanks for the report, will look into this as this should obviously not occur.
