### ISSUE TITLE
Kicking the DM is possible

### ISSUE THREAD

**Issue by raffitz** [Kruptein/PlanarAlly#288]
Greetings. I'm playing around with 0.19.3, and I ran into the following issue: I opened the invite url while still logged as the DM and am now listed as a player as well as being DM. This does not de-escalate my permissions, so it's not terrible. When I log in, I have "Session" as well as "username/Session" listed, and both go to the same place, both as DM.

If in the DM Options panel I kick myself, the real issue starts:

The client stalls in the browser, and the server outputs the following to stderr (though not to the log file):

```
message async handler error
Traceback (most recent call last):
  File "/home/username/.local/lib/python3.8/site-packages/peewee.py", line 6741, in get
    return clone.execute(database)[0]
  File "/home/username/.local/lib/python3.8/site-packages/peewee.py", line 4184, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/username/.local/lib/python3.8/site-packages/engineio/asyncio_server.py", line 420, in _trigger_event
    ret = await self.handlers[event](*args)
  File "/home/username/.local/lib/python3.8/site-packages/socketio/asyncio_server.py", line 528, in _handle_eio_message
    await self._handle_connect(sid, pkt.namespace)
  File "/home/username/.local/lib/python3.8/site-packages/socketio/asyncio_server.py", line 413, in _handle_connect
    success = await self._trigger_event('connect', namespace, sid,
  File "/home/username/.local/lib/python3.8/site-packages/socketio/asyncio_server.py", line 493, in _trigger_event
    ret = await self.handlers[namespace][event](*args)
  File "/home/username/PlanarAlly/server/api/socket/connection.py", line 82, in connect
    await load_location(sid, location)
  File "/home/username/PlanarAlly/server/auth.py", line 43, in wrapped
    return await fn(*args, **kwargs)
  File "/home/username/PlanarAlly/server/api/socket/location.py", line 35, in load_location
    **LocationUserOption.get(user=user, location=location).as_dict()
  File "/home/username/.local/lib/python3.8/site-packages/peewee.py", line 6318, in get
    return sq.get()
  File "/home/username/.local/lib/python3.8/site-packages/peewee.py", line 6744, in get
    raise self.model.DoesNotExist('%s instance matching query does '
models.campaign.LocationUserOptionDoesNotExist: <Model: LocationUserOption> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."location_id", "t1"."user_id", "t1"."pan_x", "t1"."pan_y", "t1"."zoom_factor", "t1"."active_layer_id" FROM "location_user_option" AS "t1" WHERE (("t1"."location_id" = ?) AND ("t1"."user_id" = ?)) LIMIT ? OFFSET ?
Params: [7, 1, 1, 0]
```

I was able to salvage the situation by re-accessing the invite link.

**Comment by Kruptein** [comment]
haha that's interesting, thanks for the report

**Comment by chisaipete** [comment]
I experienced this as well.  It's pretty easy to get into a state where the DM is kickable:
Paste invite link in discord for others to join.  Forget and click same link.  Now you are a player and DM!

**Comment by Kruptein** [comment]
Yeah it's a stupid oversight, should be resolved by next release
