### ISSUE TITLE
[BUG] Cant delete location

### ISSUE THREAD

**Issue by Dhy19971** [Kruptein/PlanarAlly#344]
**Describe the bug**
Once the procedure to delete a position has been made, it disappears. If you refresh the page reappears

**To Reproduce**
1. Go to location menu
2. Click on gear
3. Scroll down to delete location
4. no error only bag

**Expected behavior**
The selected position disappears permanently

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version Last

**Comment by Kruptein** [comment]
Is there anything in the web console or server console ?

**Comment by Kruptein** [comment]
Also just to make sure, is this a location where you or one of the players is located?
If that's the case it should not be possible to click the remove Location button

**Comment by Dhy19971** [comment]
There is no player in location.

`(Press CTRL+C to quit)
2020-05-11 16:34:39,480 - INFO - User DangerMaster connected with identifier 441c6af3b0044d0bae31e1fabb01ea65 (connection.py:44)
2020-05-11 16:34:47,978 - INFO - User DangerMaster disconnected with identifier 441c6af3b0044d0bae31e1fabb01ea65 (connection.py:112)
2020-05-11 16:34:48,323 - INFO - User DangerMaster connected with identifier 6b386f235c354758960046ba6e015cd2 (connection.py:44)
Task exception was never retrieved
future: <Task finished coro=<AsyncServer._handle_event_internal() done, defined at site-packages\socketio\asyncio_server.py:469> exception=IntegrityError('FOREIGN KEY constraint failed')>
Traceback (most recent call last):
  File "site-packages\peewee.py", line 3099, in execute_sql
sqlite3.IntegrityError: FOREIGN KEY constraint failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\socketio\asyncio_server.py", line 470, in _handle_event_internal
  File "site-packages\socketio\asyncio_server.py", line 498, in _trigger_event
  File "server\auth.py", line 46, in wrapped
  File "server\api\socket\location.py", line 247, in delete_location
  File "site-packages\playhouse\signals.py", line 77, in delete_instance
  File "site-packages\peewee.py", line 6546, in delete_instance
  File "site-packages\peewee.py", line 1886, in inner
  File "site-packages\peewee.py", line 1957, in execute
  File "site-packages\peewee.py", line 2442, in _execute
  File "site-packages\peewee.py", line 3112, in execute
  File "site-packages\peewee.py", line 3106, in execute_sql
  File "site-packages\peewee.py", line 2873, in __exit__
  File "site-packages\peewee.py", line 183, in reraise
  File "site-packages\peewee.py", line 3099, in execute_sql
peewee.IntegrityError: FOREIGN KEY constraint failed`

**Comment by Dhy19971** [comment]
Sometimes I also have this problem.

Log in to a map as an administrator but I have a player's view.

Other times the maps are not loaded immediately.

Both things are solved by loading the page several times.

I keep the bailouts of previous versions of planaralmente .. can create problems?

It would be very useful to be able to manage assets and maps directly from the windows folder.

**Comment by Kruptein** [comment]
Can you mail me your save file for more in-depth debugging? [mailto:info@darragh.dev]

These are strange bugs I haven't encountered myself so I have the feeling something is off with your save.

What do you mean with bailouts ?

Managing files/assets from within the windows folder is not feasible.  If you start moving things around PA will have no idea where to look for them as it will only have the original location.  There are also space improvements to make sure that only 1 physical file exists if the file is used by multiple users.

**Comment by Dhy19971** [comment]
By saving I mean the sql file that is specified in the configuration txt.

I sent you all my server directly. Old version and new.

**Comment by Kruptein** [comment]
The good news is that I can reproduce the error with your save file.  Now figuring out what's going wrong.

**Comment by Kruptein** [comment]
Ok found it

**Comment by Dhy19971** [comment]
Great .. is it any mistake of mine that I can solve or is it just a bug to fix?

**Comment by Kruptein** [comment]
It's a mistake on my end, there was a divergence between old saves upgrading to the newest format and newly created files.  Your save files helped me figuring this out so thanks a lot.

0.20.1 is building and should be soon available to download
