### ISSUE TITLE
[BUG] Upload fails when uploading large number of assets

### ISSUE THREAD

**Issue by sevzero** [Kruptein/PlanarAlly#503]
**Describe the bug**
When uploading large numbers of assets (500+) at a time, the upload progress stops, usually between 150-250 files.

**To Reproduce**
* Open asset management page
* Click upload button
* Navigate to directory with large number of assets and select all
* Progress bar seems to freeze between 150 and 250 uploaded files and no more files are uploaded

**Expected behavior**
All files should be uploaded successfully

**Desktop:**
 - OS: Windows (browser), PlanarAlly running in docker on Debian 9
 - Browser: Replicated in Firefox and Chrome
 - Version FF 79.0, Chrome 84.0.4147.135

**Additional context**
When the upload process hangs the following stack trace is produced
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/socketio/asyncio_server.py", line 470, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/usr/local/lib/python3.7/site-packages/socketio/asyncio_server.py", line 498, in _trigger_event
    ret = await self.handlers[namespace][event](*args)
  File "/PlanarAlly/server/api/socket/asset_manager.py", line 37, in get_folder
    folder = Asset[folder]
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 6152, in __getitem__
    return self.get_by_id(key)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 6395, in get_by_id
    return cls.get(cls._meta.primary_key == pk)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 6384, in get
    return sq.get()
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 6807, in get
    return clone.execute(database)[0]
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 1886, in inner
    return method(self, database, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 1957, in execute
    return self._execute(database)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 2129, in _execute
    cursor = database.execute(self)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 3112, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 3106, in execute_sql
    self.commit()
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 2873, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 183, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 3099, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: row value misused
```

**Comment by dthv** [comment]
Upload stopping [has been reported](https://discord.com/channels/695640902135185449/696105888808697917/767461554957975553) also for few, but large files.
