### ISSUE TITLE
[BUG] Moving a token generates an error on the server

### ISSUE THREAD

**Issue by LDeeJay1969** [Kruptein/PlanarAlly#519]
Moving a token generates an error message on the server:

Task exception was never retrieved
future: <Task finished coro=<AsyncServer._handle_event_internal() done, defined at /home/me/.local/lib/python3.7/site-packages/socketio/asyncio_server.py:469> exception=KeyError('position')>
Traceback (most recent call last):
  File "/home/me/.local/lib/python3.7/site-packages/socketio/asyncio_server.py", line 470, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/home/me/.local/lib/python3.7/site-packages/socketio/asyncio_server.py", line 498, in _trigger_event
    ret = await self.handlers[namespace][event](*args)
  File "/home/me/Downloads/PlanarAlly-dev/server/auth.py", line 46, in wrapped
    return await fn(*args, **kwargs)
  File "/home/me/Downloads/PlanarAlly-dev/server/api/socket/shape/__init__.py", line 125, in update_shape_positions
    points = data_shape["position"]["points"]
KeyError: 'position'

**To Reproduce**
1. Create a new campaign
2. Right-Click on the grid
3. Select "Create Basic Token"
4. Move the token to snap to grid.
5. See error

**Expected behavior**
No errors on the server for this 'basic' usage.

**Desktop (please complete the following information):**
 - OS: Linux Mint 19
 - Browser:  Firefox 80.0, Chromium 84.0, Chrome 85.0
 - Version:  22.3

**Comment by LDeeJay1969** [comment]
The new location of the token/asset isn't saved in the database making it impossible to (re)position objects.

**Comment by LDeeJay1969** [comment]
Nevermind..... re-rebuilding the client solved both issues in one go. Apologies.
