### ISSUE TITLE
[BUG]  docker failing to start after upgrade 

### ISSUE THREAD

**Issue by hakarune** [Kruptein/PlanarAlly#597]
**Describe the bug**
Upgraded the Docker image and now it fails to start...

**Database**
V32:  [https://1drv.ms/u/s!AvxMjEffoUYWgeYgZYU5GayIgzB0KA?e=pSkNUj](https://1drv.ms/u/s!AvxMjEffoUYWgeYgZYU5GayIgzB0KA?e=pSkNUj)
V31:  [https://1drv.ms/u/s!AvxMjEffoUYWgeYhLd9x9arjdJNhAg?e=PoFvbv](https://1drv.ms/u/s!AvxMjEffoUYWgeYhLd9x9arjdJNhAg?e=PoFvbv)

**Logs**
```
Traceback (most recent call last):
  File "/planarally/save.py", line 678, in check_save
    upgrade(save_version)
  File "/planarally/save.py", line 476, in upgrade
    "ALTER TABLE shape ADD COLUMN angle INTEGER NOT NULL DEFAULT 0"
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 3106, in execute_sql
    self.commit()
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2873, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 183, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 3099, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: attempt to write a readonly database
2020-12-14 02:30:52,913 - ERROR - ERROR: Could not start server (save.py:681)
2020-12-14 02:31:46,009 - WARNING - Save format 32 does not match the required version 43! (save.py:661)
2020-12-14 02:31:46,011 - WARNING - Attempting upgrade (save.py:663)
2020-12-14 02:31:46,012 - WARNING - Backing up old save as /planarally/save_backups/planar.sqlite.32 (save.py:674)
2020-12-14 02:31:46,023 - WARNING - Starting upgrade to 33 (save.py:676)
2020-12-14 02:31:46,025 - ERROR - attempt to write a readonly database (save.py:680)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 3099, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: attempt to write a readonly database

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/planarally/save.py", line 678, in check_save
    upgrade(save_version)
  File "/planarally/save.py", line 476, in upgrade
    "ALTER TABLE shape ADD COLUMN angle INTEGER NOT NULL DEFAULT 0"
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 3106, in execute_sql
    self.commit()
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2873, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 183, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 3099, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: attempt to write a readonly database
2020-12-14 02:31:46,031 - ERROR - ERROR: Could not start server (save.py:681)
```

**Comment by Kruptein** [comment]
Hey, this is related to a change in the docker image to no longer run as root, but as user 9000,

Check the chown commands here, for more info on how to migrate https://www.planarally.io/tutorial/setup/self-hosting/#docker-container

sorry for the inconvenience

**Comment by hakarune** [comment]
> Hey, this is related to a change in the docker image to no longer run as root, but as user 9000,
> 
> Check the chown commands here, for more info on how to migrate https://www.planarally.io/tutorial/setup/self-hosting/#docker-container
> 
> sorry for the inconvenience

I was running it as a standard user and not root, but I don't have a user with the ID 9000 and the data storage is on an NTFS drive that is mounted `775`. I tried to run with the PUID as `9000 `and the PGID as `100` (user) so it can write to the location, but same exact error. I also tried removing the PGID & PUID variables, and still no dice. Is the only way for this to work is to move my  data & assets to a new drive and `chmod 775 9000:9000`?

**Comment by hakarune** [comment]
> Hey, this is related to a change in the docker image to no longer run as root, but as user 9000,
> 
> Check the chown commands here, for more info on how to migrate https://www.planarally.io/tutorial/setup/self-hosting/#docker-container
> 
> sorry for the inconvenience

So only way I got it to work was to move the files from the NTFS drive and move them to an internal m.2 drive where I can chown & chmod the files. As long as the assets and data don't get too big it won't be a problem, but this is a very unfortunate change. My external is a 4TB drive and the m.2 is a very small boot backup drive.

**Comment by Kruptein** [comment]
I understand the problem, sorry for the inconvenience :c

but you managed to resolve it then or is there still a problem with your current setup ?

> I was running it as a standard user and not root,
I meant the user that is used in the actual docker image, not the user running the docker image

**Comment by hakarune** [comment]
> I understand the problem, sorry for the inconvenience :c
> 
> but you managed to resolve it then or is there still a problem with your current setup ?
> 
> > I was running it as a standard user and not root,
> 
> I meant the user that is used in the actual docker image, not the user running the docker image

No everything is running again and only 2 maps disappeared, but that is an easy fix. Thank you.
