### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'aiojobs'

### ISSUE THREAD

**Issue by PalasX** [Kruptein/PlanarAlly#967]
**Describe the bug**
Cannot run DEV or LATEST docker container, AMD64

**To Reproduce**
start a new docker container with LATEST or DEV version.

Error log:
ModuleNotFoundError: No module named 'aiojobs'
Traceback (most recent call last):
  File "/planarally/src/planarserver.py", line 25, in <module>
    import api.http
  File "/planarally/src/api/http/__init__.py", line 6, in <module>
    from api.socket.constants import GAME_NS
  File "/planarally/src/api/socket/__init__.py", line 1, in <module>
    from . import (
  File "/planarally/src/api/socket/asset.py", line 6, in <module>
    from app import app, sio
  File "/planarally/src/app.py", line 6, in <module>
    import aiojobs.aiohttp

Missing AIOJOBS python library in docker image?

**Desktop (please complete the following information):**
 - OS: ubuntu, docker

**Comment by Kruptein** [comment]
Yep that was my bad, this is fixed in release 2022.2.2 which just got out.

Thanks for the report and sorry for the inconvenience!

**Comment by PalasX** [comment]
Thank you for the quick response and all the work you put into this AWESOME project!!!
